### ISSUE TITLE
Pedido de Segundo Parcial

### ISSUE THREAD

**Issue by FriendlyFiubense** [gcc-cdimatteo/EBTI-Empresas-de-Base-Tecnologica#1]
Buenas noches,

Te quería consultar si tenes disponible el parcial de legal y/o recuperatorio para chusmear que tomaron 👀 

Desde ya, muchas gracias!

**Comment by gcc-cdimatteo** [comment]
No. No me dejaron sacarle foto. Si conseguís este cuatri abrí PR y lo subimos.
